### ISSUE TITLE
bird-watcher: add example for discards in array pattern

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#1014]
The `tracks-on-tracks-on-tracks` exercise wants students to use a discard in their implementation. However, the introduction.md document of that exercise does not explain how that works. We should add a small example on how to use discards in array patterns. Note: this very same change needs to happen in the `introduction.md` document of the `arrays` concept.

**Comment by aage** [comment]
@ErikSchierboom I've added a PR for this: https://github.com/exercism/fsharp/pull/1039

Could you have a look?
