### ISSUE TITLE
tracks-on-tracks-on-tracks: add example for discards in list pattern

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#1015]
The `tracks-on-tracks-on-tracks` exercise wants students to use a discard in their implementation. However, the introduction.md document of that exercise does not explain how that works. We should add a small example on how to use discards in list patterns. Note: this very same change needs to happen in the `introduction.md` document of the `lists` concept.

**Comment by aage** [comment]
I have a question about this exercise in general; is the intent of the exercise _not_ to use the default functions within the `List module` (`List.rev` etc.)?
If not, this isn't made clear in the instruction I think. If yes, then you wouldn't necessarily need to use a discard to solve this exercise, do you?

**Comment by aage** [comment]
@ErikSchierboom I've added a PR with a suggestion for this issues: https://github.com/exercism/fsharp/pull/1028
* You mention that the same change is needed in the `lists` concept, where can I find this? If you like this change I can also add it there.
* In the example _above_ my commited change, the `rec` keyword is used in the `describe` function, but is unnecessary since there's no recursion used. I've omitted this in my change, but would suggest this be removed from that example as well. What do you think?

**Comment by ErikSchierboom** [comment]
@aage Nice! I've commented.

> You mention that the same change is needed in the lists concept, where can I find this? If you like this change I can also add it there.

Each concept has its own `introduction.md` and `about.md` documents. For the `lists` concept, those are found at:

- https://github.com/exercism/fsharp/blob/main/concepts/lists/introduction.md
- https://github.com/exercism/fsharp/blob/main/concepts/lists/about.md

You can basically copy the changes from your PR to those files. In the `about.md` file, you're free to expand on things a bit more if needed (e.g. you can add links).

> In the example above my commited change, the rec keyword is used in the describe function, but is unnecessary since there's no recursion used. I've omitted this in my change, but would suggest this be removed from that example as well. What do you think?

That should absolutely be removed. A separate PR is much appreciated!

**Comment by aage** [comment]
@ErikSchierboom This issue can be closed right? Since the PR is merged into main.

**Comment by ErikSchierboom** [comment]
Correct! Small note: you can use specific keywords to reference an issue from a PR: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword. E.g. if you use `Closes #123`, upon merging the PR issue 123 would be closed.
