### ISSUE TITLE
Upgrade to .NET 6

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#1031]
With .NET 6 released, we should be updating all exercises to .NET 6. This will allow students to use F# 6, which has some nice features.

Note that we should make sure that the [fsharp-test-runner](https://github.com/exercism/fsharp-test-runner/), [fsharp-representer](https://github.com/exercism/fsharp-representer/) and [fsharp-analyzer](https://github.com/exercism/fsharp-analyzer/) all work. We likely want to update them to .NET 6 too.

**Comment by aage** [comment]
@ErikSchierboom Is there any description of how the other tools you mentioned can be tested? The upgrading to .NET 6 is something I could look into, but I don't know how I could tell if I'd broken something.

> Note that we should make sure that the [fsharp-test-runner](https://github.com/exercism/fsharp-test-runner/), [fsharp-representer](https://github.com/exercism/fsharp-representer/) and [fsharp-analyzer](https://github.com/exercism/fsharp-analyzer/) all work. We likely want to update them to .NET 6 too.

**Comment by ErikSchierboom** [comment]
Ah, this issue should actually have been closed by https://github.com/exercism/fsharp/pull/1042, sorry!

**Comment by aage** [comment]
No prob!
