### ISSUE TITLE
difference-of-squares: Tests not running

### ISSUE THREAD

**Issue by galambborong** [exercism/fsharp#1035]
The online testing for the DifferenceOfSquares exercise doesn't currently work:

![image](https://user-images.githubusercontent.com/57960614/141343575-dc907550-1e5b-4f74-a4f3-d116388e778b.png)

The same code passes the tests locally on my system. Looks to me like the `Skip` needs removing from the `[<Fact>]` attributes.

**Comment by ErikSchierboom** [comment]
@galambborong This should now be fixed! Could you re-run the tests to verify this?

**Comment by galambborong** [comment]
Thanks @ErikSchierboom! The tests are now running, but keep timing out. The code is pretty simple, so not sure what else to try - and they're all passing locally (in 26ms):

![image](https://user-images.githubusercontent.com/57960614/142616499-e9e0d0b7-0513-4253-9357-8fcaef4bdb77.png)

I'll retry again later and see if it works.

Thanks again!

**Comment by ErikSchierboom** [comment]
Could you post your code here?

**Comment by galambborong** [comment]
Of course:

```f#
module DifferenceOfSquares

let square n = n * n

let squareOfSum number = [ 1 .. number ] |> List.sum |> square

let sumOfSquares number = [ 1 .. number ] |> List.sumBy square

let differenceOfSquares number =
    squareOfSum number - sumOfSquares number
```

**Comment by ErikSchierboom** [comment]
Should be fixed now! Could you try re-running the tests?

**Comment by galambborong** [comment]
Amazing, thanks @ErikSchierboom - that's working now! Really grateful for you looking into it.
