### ISSUE TITLE
Unable to run tests on website.

### ISSUE THREAD

**Issue by parkeradam** [exercism/fsharp#1046]
In the Two-fer exercise, I have the following solution which works on local and passes all tests but seems to simply be timing out on the website. 
```fsharp
﻿module TwoFer

let twoFer (input: string option) : string =
    let returnString = sprintf "One for %s, one for me."

    match input with
    | Some (value) -> returnString value
    | None -> returnString "you"
```

Would be nice to know why it keeps failing.

Thanks in advance and good work on the site :)

**Comment by ErikSchierboom** [comment]
Should be fixed now! Could you try re-running the tests?

**Comment by parkeradam** [comment]
Seems to be fixed thanks :)
