### ISSUE TITLE
Some exercises fail to unlock on the concept syllabus

### ISSUE THREAD

**Issue by colinleach** [exercism/fsharp#1048]
Anagram : depends on Log Levels
Bank Account : depends on Interest is Interesting; Tracks on Tracks on Tracks
Strain : depends on Bird Watcher; Tracks on Tracks on Tracks; Cars, Assemble!

In all cases when I click through to a dependency, exercism confirms that I have completed it.

Low-priority but puzzling.

**Comment by ErikSchierboom** [comment]
We've just fixed this issue! Everything should unlock properly now.
