### ISSUE TITLE
The test runner infrastructure seems to have issues

### ISSUE THREAD

**Issue by aage** [exercism/fsharp#1050]
Getting `An error occurred while running your tests. ` while submitting compiling solutions and running tests in UI.

**Comment by ErikSchierboom** [comment]
I can't seem to reproduce. Could you check if the issue still persists?

**Comment by aage** [comment]
Just now in the Anagram exercise. This code builds locally and tests pass, in the online editor I get error in attached image.
```fsharp
module Anagram

open System

let findAnagrams sources target =

    let areAnagrams (lhs: string) (rhs: string) =
        let normalize (s: string) =
            Seq.sort (s.ToLower())
            |> Array.ofSeq
            |> fun xs -> new string (xs)

        normalize lhs = normalize rhs
        && not (lhs.ToLower() = rhs.ToLower())

    sources |> List.filter (areAnagrams target)
```


![image](https://user-images.githubusercontent.com/984017/144031595-8b58aed2-7b2b-4aa4-a4f0-0c0893bc5d79.png)

**Comment by ErikSchierboom** [comment]
@aage This should now be fixed.

**Comment by aage** [comment]
Yes!
