### ISSUE TITLE
Why are all the tests with the Skip property?

### ISSUE THREAD

**Issue by Sprootch** [exercism/fsharp#1051]
[<Fact(Skip = "Remove this Skip property to run this test")>]

**Comment by jrr** [comment]
So that you only have to deal with one at a time. The idea is that you write code to pass one test, then you enable the next test, write code to pass that one, and keep repeating until they're all passing.

**Comment by Sprootch** [comment]
Ok I get it. 
Is it foreseen that the online editor is able to activate/ignore some tests?

**Comment by ErikSchierboom** [comment]
Yes. The online editor unskips the tests first.
