### ISSUE TITLE
Many solutions for SgfParsing use FParsec but cannot pass TestRunner

### ISSUE THREAD

**Issue by martinfreedman** [exercism/fsharp#1053]
This includes my solution, hence me noticing this.

Only 1 out of 7 solutions are passing. Whilst some might be out of date the ones I have checked all use FParsec.

(More generally what nuget packages should be included by default. I would suggest FSharpPlus which I have used a lot.)

**Comment by martinfreedman** [comment]
Rather than create another issue this also applies to Wordy, for which FParsec is recommended!

**Comment by martinfreedman** [comment]
I am sure the issue applies to other exercises I recall a json one (cannot remember the name) which different packages were used in different solutions.

**Comment by ErikSchierboom** [comment]
Yep, this is an oversight. The FParsec library isn't pre-installed. Will be fixed by https://github.com/exercism/fsharp-test-runner/pull/69
