### ISSUE TITLE
Make Diamond exercise compile instead of // TODO

### ISSUE THREAD

**Issue by aage** [exercism/fsharp#1071]
There seems to be no point in having a not compiling `.fs` exercise file and it doesn't seem consistent where other exercises *do* have the default `failwith "You need to implement this function."` error.

**Comment by ErikSchierboom** [comment]
Agreed! Are you interested in submitting a PR?

**Comment by aage** [comment]
Yes!

Here it is: https://github.com/exercism/fsharp/pull/1072
