### ISSUE TITLE
Exercise: Binary Search

### ISSUE THREAD

**Issue by CodeMan99** [exercism/fsharp#1091]
For the [Binary Search](https://exercism.org/tracks/fsharp/exercises/binary-search) exercise, there is nothing to prevent an implementation using [`Array.tryFindIndex`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-arraymodule.html#tryFindIndex). So this implementation is accepted.

```fsharp
module BinarySearch

let find input value = Array.tryFindIndex ((=) value) input
```

This is probably not the goal of the exercise and should probably be rejected. Or, at least, a mention in description of the exercise to avoid that specific helper (similar to the [Accumulate](https://exercism.org/tracks/fsharp/exercises/accumulate) exercise).

**Comment by ErikSchierboom** [comment]
Good idea. The way to have it be mentioned in the description is to add a `.docs/instructions.append.md` file to the exercise's directory. Like https://github.com/exercism/fsharp/blob/main/exercises/practice/accumulate/.docs/instructions.append.md

Would you be willing to submit a PR?

**Comment by CodeMan99** [comment]
> Would you be willing to submit a PR?

Sure thing. Wanted to make sure I was at least strolling down the right avenue 😀

**Comment by CodeMan99** [comment]
PR #1094 was merged. Closing.
