### ISSUE TITLE
Booking up for beauty example solution invalid

### ISSUE THREAD

**Issue by vaeng** [exercism/fsharp#1232]
It seems like the implementation for the AM PM string representation has changed.
The current proof solution from the repository does not work with the current test.

The current F# implementation does not use a space any longer between the time and the AM/PM.

https://github.com/exercism/fsharp/blob/930ca1cf056961485f7d03cafe0ebff52984a091/exercises/concept/booking-up-for-beauty/BookingUpForBeautyTests.fs#L161

**Comment by KyleDickersonComposer** [comment]
You can pass a date format into the ToString method of DateTime. 
<img width="1402" alt="Screenshot 2024-04-11 at 10 13 16 PM" src="https://github.com/exercism/fsharp/assets/44070073/9abfb4ef-ad1d-4cf5-814d-bdd48eaced56">

**Comment by ErikSchierboom** [comment]
There is something weird going on, as the tests have `.Replace('\u202F', ' ')` appended to them, but they still don't work. Whereas adding `.Replace('\u202F', ' ')` to the implementation works. I'll have a dig.

**Comment by ErikSchierboom** [comment]
I've just upgraded to the latest version of the exercise and now the tests _do_ pass. Could you check that works for you @vaeng?
