### ISSUE TITLE
Using FsUnit for more expressive tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#203]
At the moment, the exercises used NUnit's `Assert` class' methods to verify behavior. While this works, it's not really a nice functional API. Perhaps it would make sense to use [FsUnit](http://fsprojects.github.io/FsUnit/), which provides a functional wrapper around the tests.

As an example, this is how an assertion looks like today:

``` fsharp
Assert.That(1, Is.EqualTo(1))
```

And this is how it would look with FsUnit:

``` fsharp
1 |> should equal 1
```

I much prefer the second option. It would require people to install an additional package before the tests can be run, but that won't really be a problem as I'm working on creating a pre-defined project for each exercise, which would already contain the required libraries.

cc @jwood803 @rmunn @robkeim @rebelwarrior @pminten

**Comment by robkeim** [comment]
+1
I think it would be a good opportunity to give people an opportunity to see more functional F# code as they're learning. I'm not familiar at all with FsUnit, so I don't know how "complete" it is in terms of the functionality that we're using from NUnit today.

Probably the easiest way to find out would be to take some sample tests and convert them. If you add it into a project I'd be more than happy to pitch in converting some of the tests.

**Comment by ErikSchierboom** [comment]
@robkeim Great! Really appreciate it. I'll see if I can get this setup tomorrow.

**Comment by rmunn** [comment]
Oh, definitely! And there are some tests, particularly the ones where you have to re-implement a basic data structure like linked lists, that could greatly benefit from showing off something like [FsCheck](https://fscheck.github.io/FsCheck/index.html) as well. Precisely *when* you'd want to teach people to use FsCheck (and Paket to install it) is a good question, but I think at some point when the tests start hitting intermediate difficulty might be best. See also my [comment on #32](https://github.com/exercism/xfsharp/issues/32#issuecomment-243512237) for more thoughts about Paket and FAKE.

**Comment by ErikSchierboom** [comment]
Good point about also introducing FsCheck, it is also ideally suited for the `diamond` exercise (in fact that's how I originally solved it). The only tricky thing is, as you said, determining when to introduce it.

**Comment by ErikSchierboom** [comment]
@robkeim I think I'll wait with this until I have the new setup (with FAKE and such) working, which is depending on the CLI to be updated (see [this PR](https://github.com/exercism/x-api/pull/124)).

**Comment by robkeim** [comment]
Ok sounds good!

**Comment by jwood803** [comment]
Apologies @ErikSchierboom, for some reason I'm not getting notifications.

I do love FsUnit and I'm all for it to express tests better. :)

**Comment by mattcbaker** [comment]
I'd love to help convert tests once this is ready to begin.

**Comment by ErikSchierboom** [comment]
I'll hold you to that promise :)

**Comment by tushartyagi** [comment]
@ErikSchierboom I would love to contribute to this change. I am a F# newbie so I guess this will help me in learning FsUnit as well.

Now that [x-api/PR124](https://github.com/exercism/x-api/pull/124) is closed, have you started working on your setup?

**Comment by ErikSchierboom** [comment]
@tushartyagi I have not yet worked on the new setup, which will be based on .NET Core. As part of the process of converting the exercises to .NET Core, we will be creating a [project file](#309) for each exercise. This will allow us to add the additional package dependency (FsUnit) automatically. Another part of the .NET Core conversion setup is to use xUnit instead of NUnit as the testing framework. As both of these frameworks are supported by FsUnit, I think it would be super convenient if we had the FsUnit tests in place, as we can then easily swap out the underlying test framework by simply replacing the opened module! 😎 

All in all, I would wholeheartedly welcome you working on this issue! The help is much appreciated.

**Comment by rmunn** [comment]
I'd like to see this issue stay open, so this is a contentless update so that the auto-close bot will leave the issue open.
