### ISSUE TITLE
Replace NUnit with Xunit

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#297]
Xunit has slowly but steadily been replacing NUnit as the favored testing framework. Virtually all open-source Microsoft code now uses Xunit as the unit-testing framework. The integration with .NET Core is thus also better, as Microsoft has invested in Xunit for its own software and thus has to keep it running. An example of this improved integration is the fact that there is an Xunit template available in the .NET CLI.

Note: we should first do #203, as that would make this transition hopefully just a matter of changing package references :)

**Comment by robkeim** [comment]
The same conversion is happening in C# as part of https://github.com/exercism/xcsharp/issues/193

**Comment by ErikSchierboom** [comment]
Fixed by #348.
