### ISSUE TITLE
Replace [<TestCase>] tests with individual tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#298]
We have several places where we use `[TestCase]` to create a single test with multiple input values. While efficient (no code duplication), this is not the best of user experiences as it makes it harder to run a single test and also doesn't really allow us to mark the various input values with a descriptive text. It also doesn't align with how canonical data for exercises is defined, which only works on single test cases.

Consider the `isogram` exercises's tests:

```fsharp
[<TestCase("duplicates", ExpectedResult = true)>]
[<TestCase("eleven", ExpectedResult = false, Ignore = "Remove to run test case")>]
[<TestCase("subdermatoglyphic", ExpectedResult = true, Ignore = "Remove to run test case")>]
[<TestCase("Alphabet", ExpectedResult = false, Ignore = "Remove to run test case")>]
[<TestCase("thumbscrew-japingly", ExpectedResult = true, Ignore = "Remove to run test case")>]
[<TestCase("Hjelmqvist-Gryb-Zock-Pfund-Wax", ExpectedResult = true, Ignore = "Remove to run test case")>]
[<TestCase("Heizölrückstoßabdämpfung", ExpectedResult = true, Ignore = "Remove to run test case")>]
[<TestCase("the quick brown fox", ExpectedResult = false, Ignore = "Remove to run test case")>]
[<TestCase("Emily Jung Schwartzkopf", ExpectedResult = true, Ignore = "Remove to run test case")>]
[<TestCase("éléphant", ExpectedResult = false, Ignore = "Remove to run test case")>]
let ``Isogram correctly detects isograms`` (actual: string) =
    isogram actual
```

What's the difference between test case one and two? It's not immediately obvious. The [canonical-data](https://github.com/exercism/x-common/blob/master/exercises/isogram/canonical-data.json) of this exercise looks much nicer. I think we should convert the [<TestCase>] tests to individual tests.

**Comment by robkeim** [comment]
This is also being discussed in the C# track https://github.com/exercism/xcsharp/issues/194

**Comment by robkeim** [comment]
Here are the list of exercises using the `TestCase` attribute:
- [ ] [acronym](https://github.com/exercism/xfsharp/tree/master/exercises/acronym)
- [ ] [atbash-cipher](https://github.com/exercism/xfsharp/tree/master/exercises/atbash-cipher)
- [ ] [clock](https://github.com/exercism/xfsharp/tree/master/exercises/clock)
- [ ] [diamond](https://github.com/exercism/xfsharp/tree/master/exercises/diamond)
- [ ] [grep](https://github.com/exercism/xfsharp/tree/master/exercises/grep)
- [ ] [isogram](https://github.com/exercism/xfsharp/tree/master/exercises/isogram)
- [ ] [largest-series-product](https://github.com/exercism/xfsharp/tree/master/exercises/largest-series-product)
- [ ] [luhn](https://github.com/exercism/xfsharp/tree/master/exercises/luhn)
- [ ] [matrix](https://github.com/exercism/xfsharp/tree/master/exercises/matrix)
- [ ] [meetup](https://github.com/exercism/xfsharp/tree/master/exercises/meetup)
- [ ] [nth-prime](https://github.com/exercism/xfsharp/tree/master/exercises/nth-prime)
- [ ] [perfect-numbers](https://github.com/exercism/xfsharp/tree/master/exercises/perfect-numbers)
- [ ] [pig-latin](https://github.com/exercism/xfsharp/tree/master/exercises/pig-latin)
- [ ] [protein-translation](https://github.com/exercism/xfsharp/tree/master/exercises/protein-translation)
- [ ] [pythagorean-triplet](https://github.com/exercism/xfsharp/tree/master/exercises/pythagorean-triplet)
- [ ] [raindrops](https://github.com/exercism/xfsharp/tree/master/exercises/raindrops)
- [ ] [roman-numerals](https://github.com/exercism/xfsharp/tree/master/exercises/roman-numerals)
- [ ] [series](https://github.com/exercism/xfsharp/tree/master/exercises/series)
- [ ] [simple-linked-list](https://github.com/exercism/xfsharp/tree/master/exercises/simple-linked-list)

**Comment by ErikSchierboom** [comment]
Great work gathering this data @robkeim!

**Comment by balazsbotond** [comment]
I can start working on these. I will always leave a comment here before starting to convert the tests for an exercise - this way you'll know which ones are still up for grabs :)

**Comment by robkeim** [comment]
Sounds great, thanks @balazsbotond.

**Comment by ErikSchierboom** [comment]
That would be brilliant @balazsbotond1

**Comment by balazsbotond** [comment]
Starting to work on: acronym

**Comment by robkeim** [comment]
@ErikSchierboom I'm closing this issue as this should now be obsolete with the move to using test generators.

**Comment by ErikSchierboom** [comment]
@robkeim Good point.
