### ISSUE TITLE
Check for out-of-date test data

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#305]
The canonical data of the various exercises regularly receives updates. Some of our exercises will be using outdated or incomplete data. We should try to fix this.

**Comment by ErikSchierboom** [comment]
- [ ] hello-world
- [ ] leap
- [ ] bob
- [ ] gigasecond
- [ ] difference-of-squares
- [ ] rna-transcription
- [ ] sum-of-multiples
- [ ] space-age
- [ ] grains
- [ ] hamming
- [ ] nucleotide-count
- [ ] accumulate
- [ ] raindrops
- [ ] grade-school
- [ ] pangram
- [ ] etl
- [ ] clock
- [ ] beer-song
- [ ] triangle
- [ ] robot-name
- [ ] error-handling
- [ ] scrabble-score
- [ ] proverb
- [ ] protein-translation
- [ ] kindergarten-garden
- [ ] queen-attack
- [ ] strain
- [ ] isogram
- [ ] sieve
- [ ] phone-number
- [ ] perfect-numbers
- [ ] robot-simulator
- [ ] binary-search
- [ ] secret-handshake
- [ ] word-count
- [ ] allergies
- [ ] twelve-days
- [ ] meetup
- [ ] anagram
- [ ] series
- [ ] simple-linked-list
- [ ] acronym
- [ ] matrix
- [ ] all-your-base
- [ ] largest-series-product
- [ ] house
- [ ] pythagorean-triplet
- [ ] saddle-points
- [ ] pascals-triangle
- [ ] list-ops
- [ ] prime-factors
- [ ] roman-numerals
- [ ] binary-search-tree
- [ ] ocr-numbers
- [ ] dot-dsl
- [ ] parallel-letter-frequency
- [ ] linked-list
- [ ] simple-cipher
- [ ] tree-building
- [ ] scale-generator
- [ ] atbash-cipher
- [ ] food-chain
- [ ] grep
- [ ] custom-set
- [ ] crypto-square
- [ ] ledger
- [ ] circular-buffer
- [ ] luhn
- [ ] bank-account
- [ ] markdown
- [ ] run-length-encoding
- [ ] book-store
- [ ] tournament
- [ ] word-search
- [ ] bowling
- [ ] transpose
- [ ] nth-prime
- [ ] palindrome-products
- [ ] pig-latin
- [ ] rail-fence-cipher
- [ ] bracket-push
- [ ] sublist
- [ ] change
- [ ] minesweeper
- [ ] diffie-hellman
- [ ] dominoes
- [ ] rectangles
- [ ] wordy
- [ ] hangman
- [ ] zebra-puzzle
- [ ] poker
- [ ] diamond
- [ ] two-bucket
- [ ] connect
- [ ] say
- [ ] react
- [ ] variable-length-quantity
- [ ] go-counting
- [ ] lens-person
- [ ] sgf-parsing
- [ ] alphametics
- [ ] zipper
- [ ] forth
- [ ] pov

**Comment by robkeim** [comment]
@ErikSchierboom this effort should be obsolete with the migration to generators, so I'm going to close this issue.
