### ISSUE TITLE
Create pre-built Docker container 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#307]
With .NET Core having great support for Docker, we could quite feasibly create a Docker container that has a working .NET Core installation as well as an installed exercism CLI. This could make starting out for those familiar with Docker a lot easier.

**Comment by WalternativE** [comment]
If I understand the ticket correctly a user would pull the container and start it up with a volume mapping. The exercism CLI would then use the mount point for this volume as the working directory which would enable the use to work on the files outside of their container with whatever tool they see as the best fit (VS, VS Code, vim, emacs, a simple text editor). Is this correct?

**Comment by ErikSchierboom** [comment]
@WalternativE That is correct. There is a more general discussion going on here: https://github.com/exercism/discussions/issues/122

**Comment by ErikSchierboom** [comment]
I've given this topic a little bit more thought, and in the end I don't think we stand to benefit much from having a Docker image with Exercism pre-installed. If someone wants to convince me otherwise, please let me know why you think this is a good idea.
