### ISSUE TITLE
Remove CircleCI and AppVeyor integration

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#345]
Similar to https://github.com/exercism/csharp/issues/340

**Comment by ErikSchierboom** [comment]
@kytrinyx Would you be so kind to remove the CircleCI and AppVeyor for the fsharp repository, similar to what you did for the csharp repository?

**Comment by kytrinyx** [comment]
Done and done!

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by robkeim** [comment]
Closed via #346
