### ISSUE TITLE
TreeBuilding exercise should not have implemented functions

### ISSUE THREAD

**Issue by danielhensilva** [exercism/fsharp#353]
I've fetched TreeBuilding and it seems to already be implemented with all tests cases passing. 
Also, there are some missing `skip` for them.

**Comment by ErikSchierboom** [comment]
@danielhensilva This is not actually a bug, but a feature! The tree building exercise is an unusual exercise in that it starts with a working implementation. Its goal is to refactor the implementation into something better, which is also why none of the test cases are being skipped (as you can verify the refactoring didn't break anything).

I hope this clears things up!

**Comment by danielhensilva** [comment]
Oh! I've got it now! Sorry about this, Erik! :)

**Comment by ErikSchierboom** [comment]
No problem!
