### ISSUE TITLE
Create issues for exercises with canonical data without generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#362]
Now that we have support for [generators](#360), we should create individual issues for each exercise with canonical data but without a generator.

**Comment by ErikSchierboom** [comment]
I'm working on this.

**Comment by ErikSchierboom** [comment]
The issues have been generated!

**Comment by robkeim** [comment]
Thanks @ErikSchierboom for getting this list built and the issues created!
