### ISSUE TITLE
Create test generators

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#363]
The canonical data of the various exercises regularly receives updates. Some of our exercises will be using outdated or incomplete data. We should try to fix this by writing test generators, support for which was added in #360.

**Comment by ErikSchierboom** [comment]
@robkeim We're down to a single page of issues! :D

**Comment by robkeim** [comment]
Woo-hoo... awesome work!!!

**Comment by robkeim** [comment]
I'm going to close this issue in favor of the separate issues we have now for the individual exercises.

**Comment by ErikSchierboom** [comment]
Good call.
