### ISSUE TITLE
Add two-fer Test Generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#364]
This issue is part of an overall initiative to complete #363.

There is no documentation yet on how to add generators, but you should be able to figure most things about by looking at the [existing generators](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs) and the base [Exercise class](https://github.com/exercism/fsharp/blob/master/generators/Exercise.fs) they inherit from.

If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by robkeim** [comment]
@ErikSchierboom why did you close this issue out of curiosity?

I don't see the generator for this in the latest code, but it looks like it has metadata here:
https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json

**Comment by ErikSchierboom** [comment]
That was a mistake, re-opening!

**Comment by ErikSchierboom** [comment]
I'm working on this
