### ISSUE TITLE
Add binary-search Test Generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#367]
This issue is part of an overall initiative to complete #363.

The canonical data on which the generator will be based can be found at [here](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search/canonical-data.json).

There is no documentation yet on how to add generators, but you should be able to figure most things about by looking at the [existing generators](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs) and the base [Exercise class](https://github.com/exercism/fsharp/blob/master/generators/Exercise.fs) they inherit from.

If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by roman-shuhov** [comment]
Implemented this one

**Comment by ErikSchierboom** [comment]
Closed by #435.
