### ISSUE TITLE
Add palindrome-products Test Generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#389]
This issue is part of an overall initiative to complete #363.

The canonical data on which the generator will be based can be found at [here](https://github.com/exercism/problem-specifications/blob/master/exercises/palindrome-products/canonical-data.json).

There is no documentation yet on how to add generators, but you should be able to figure most things about by looking at the [existing generators](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs) and the base [Exercise class](https://github.com/exercism/fsharp/blob/master/generators/Exercise.fs) they inherit from.

If you get stuck or have any questions about adding this generator, please do not hesitate to reach out!

**Comment by vrnithinkumar** [comment]
I am looking in to this.

**Comment by ErikSchierboom** [comment]
@vrnithinkumar Are you still looking into this?

**Comment by vrnithinkumar** [comment]
Sorry. I forgot about this. If I am blocking anyone, please go ahead and claim this.

**Comment by ErikSchierboom** [comment]
@vrnithinkumar Nope, if you're still interested, feel free to work on it.

**Comment by ErikSchierboom** [comment]
@vrnithinkumar Okay, if you're okay with it, I'm gonna work on this.

**Comment by vrnithinkumar** [comment]
@ErikSchierboom, Sorry for delaying it.
