### ISSUE TITLE
Wrong link on website

### ISSUE THREAD

**Issue by ReedCopsey** [exercism/fsharp#462]
This page: http://www.exercism.io/languages/fsharp/resources

Currently links to http://fpchat.com. However, that is no longer correct for the FP slack workspace. The new link is: https://fpchat-invite.herokuapp.com/

**Comment by ErikSchierboom** [comment]
Thanks for finding this! I've created a [PR](#463) to fix this.

**Comment by robkeim** [comment]
Thanks  @ReedCopsey for reporting this. I just merged @ErikSchierboom's PR so this should go live in the next day or so.
