### ISSUE TITLE
simple-linked-list exercise is solved from the start

### ISSUE THREAD

**Issue by alexyarovoy** [exercism/fsharp#472]
SimpleLinkedList.fs already contains all the implementation and passes all the tests
https://github.com/exercism/fsharp/blob/master/exercises/simple-linked-list/SimpleLinkedList.fs

I guess it's expected to be something like this:
`module SimpleLinkedList

type LinkedList<'a> = 
    | Nil 
    | Element of datum:'a * next:LinkedList<'a>

let nil = Nil

let create x n = failwith "You need to implement this function."

let isNil x = failwith "You need to implement this function."

let next x = failwith "You need to implement this function."

let datum x = failwith "You need to implement this function."

let toList x = failwith "You need to implement this function."

let fromList xs = failwith "You need to implement this function."

let reverse x = failwith "You need to implement this function."`

**Comment by ErikSchierboom** [comment]
Whoops, that is definitely a bug. Great catch! Would you be willing to create a PR to fix this? If so, you should also remove the `LinkedList` type definition, as we don't want to force people to use a specific type.

**Comment by alexyarovoy** [comment]
@ErikSchierboom created pull request:
https://github.com/exercism/fsharp/pull/473

**Comment by ErikSchierboom** [comment]
Closed by #473
