### ISSUE TITLE
pov: children as member causes error FS0072; I suggest annotating arg of graphToList

### ISSUE THREAD

**Issue by petertseng** [exercism/fsharp#522]
I preferred to have my Graph's internal representation of children be a Map:

```fsharp
type 'a Graph when 'a: comparison = {value: 'a; childrenByValue: Map<'a, 'a Graph>}
```

Of course, the test wants to be able to say `graph.children` and have that be an `'a Graph list`. That's perfectly reasonable; I'l add it as a member.

```fsharp
type 'a Graph when 'a: comparison = {value: 'a; childrenByValue: Map<'a, 'a Graph>} with
  member this.children: 'a Graph list = List.map snd (Map.toList this.childrenByValue)
```

ah, apparently not quite. This causes an error:

```
vagrant@ubuntu-xenial:~/fsharp/pov$ dotnet test
Build started, please wait...
/vagrant/pov/PovTest.fs(12,9): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [/vagrant/pov/Pov.fsproj]
```

I see. Well, apparently a type annotation may be needed, so if line 10 of https://github.com/exercism/fsharp/blob/master/exercises/pov/PovTest.fs#L10 were to change from `let rec graphToList graph` to either of the two following choices:

```fsharp
let rec graphToList (graph: 'a Graph)
```

```fsharp
let rec graphToList (graph: Graph<'a>)
```

That appears to have everything work for me. Therefore, I simply added the annotation to my test file, and submitted my solution. So the remaining questions I had:

* Were there any disadvantages of adding these type annotations?
    * Perhaps it now forces students to make their Graph generic. Before, perhaps it was possible for them to have a `Graph` that only works on strings. I wouldn't have encouraged it, but it was possible. Adding `'a Graph` makes it impossible.
* Was there another way to achieve what I wanted? Recall that my goal was to have a different internal representation of children, and only build the `'a Graph list` on demand, because the different internal representation is more convenient.

**Comment by petertseng** [comment]
EBWODP:

> so if line 12 of https://github.com/exercism/fsharp/blob/master/exercises/pov/PovTest.fs#L10

I said the wrong line but linked to the correct line. I mean line 10. Even though the error is on line 12, the place where the annotation should be added is on line 10.

**Comment by petertseng** [comment]
> Were there any disadvantages of adding these type annotations?

Perhaps it now forces students to make their Graph generic. Before, perhaps it was possible for them to have a `Graph` that only works on strings. I wouldn't have encouraged it, but it was possible. Adding `'a Graph` makes it impossible.

**Comment by ErikSchierboom** [comment]
> Were there any disadvantages of adding these type annotations?

Well, not really, except for the forcing of a generic solution (which is completely fine by the way).

> Was there another way to achieve what I wanted?

I'm not sure actually. Sometimes the generic type constraints baffle me. You could try the F# slack channel: http://fsharp.org/guides/slack/, where I'm sure there are people that better understand the generic type inference constraints.

**Comment by petertseng** [comment]
As you guessed, I needed this issue to discuss whether a PR was appropriate. I will make it happen.

> Sometimes the generic type constraints baffle me. You could try the F# slack channel: http://fsharp.org/guides/slack/, where I'm sure there are people that better understand the generic type inference constraints.

There would be a problem even if it were not generic. The following code does not compile:


```fsharp
type Hello = {value: int} with
  member this.succ = this.value + 1

let print h =
  printfn "hello %d" (h.succ)

[<EntryPoint>]
let main args =
    let h = {value = 5}
    print h
    0
```

because: `
/home/runner/main.fs(5,23): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.`

So, a type annotation is needed here as well.

```fsharp
type Hello = {value: int} with
  member this.succ = this.value + 1

let print (h: Hello) =
  printfn "hello %d" (h.succ)

[<EntryPoint>]
let main args =
    let h = {value = 5}
    print h
    0
```

(produces `hello 6` as expected)
