### ISSUE TITLE
matrix: incorrect function stub name ("col" vs "column")

### ISSUE THREAD

**Issue by jrr** [exercism/fsharp#560]
The _matrix_ exercise tests call the functions `row` and `column`, but the placeholder stubs are `row` and `col`.

https://github.com/exercism/fsharp/tree/master/exercises/matrix

It looks like the mismatch was introduced with this commit:
https://github.com/exercism/fsharp/commit/aa7f23d442dd467ed22412c579fabd24ac655c17

**Comment by ErikSchierboom** [comment]
@jrr Great catch! Would you be willing to submit a PR to fix this?

**Comment by jrr** [comment]
Sure! I was about to dive in, but hesitated when I noticed that some of the files are generated. Is the generation system documented somewhere? What's the right file to edit?

**Comment by ErikSchierboom** [comment]
@jrr The only files that are generated, are the test files. The example and stub implementation files are manually created, so you don't have to dive into the generators system (the docs can be found [here](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md)).

The file you are looking to edit is [exercises/matrix/Matrix.fs](https://github.com/exercism/fsharp/blob/master/exercises/matrix/Matrix.fs).

**Comment by ErikSchierboom** [comment]
Closed by #561.
