### ISSUE TITLE
Remove unneeded hint in gigasecond exercise

### ISSUE THREAD

**Issue by ricemery** [exercism/fsharp#566]
There is a hint in the hints file that states 

> There is a property in the DateTime class that allows you to retrieve the date without its time component.

Is this a valid hint? The unit tests pass without getting just the Date on either the input or the result.

Thx

**Comment by ErikSchierboom** [comment]
Aha, it was a valid hint before the exercise was updated to reflect the canonical data.

**Comment by ErikSchierboom** [comment]
Closed by #567.
