### ISSUE TITLE
Question - Triangle Exercise Topic

### ISSUE THREAD

**Issue by ricemery** [exercism/fsharp#570]
I have a question about the Triangle Exercise Topics.

One of the topics is "Discriminated Unions". I do not see any Discriminated Union types being used in the interface of the solution. I am wondering if this is an out of date topic for this exercise?

**Comment by robkeim** [comment]
Hello @ricemery thanks for raising this issue! This is indeed an out-of-date topic and needs to be removed. I'll go ahead and send a PR for that.

**Comment by robkeim** [comment]
This will be fixed as part of PR #572

**Comment by ricemery** [comment]
Cool. Glad to help.
