### ISSUE TITLE
Convert Yacht exercise to use discriminated union for dice values

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#577]
We currently use integers to represent a dice value, but as the value is actually very restricted (1 to 6), we should use a discriminated union.

**Comment by spencerwi** [comment]
Were you thinking something like this?

```fsharp
type DieValue =
  | One
  | Two
  | Three
  | Four
  | Five
  | Six
```

Or something more complex like a custom numeric type as outlined by Tomas Petricek [in this blog post)(http://tomasp.net/blog/fsharp-custom-numeric.aspx/index.html)?

Either way, I can do the conversion (shouldn't be too hard).

**Comment by ErikSchierboom** [comment]
That looks very cool, and is indeed what I was aiming at. I would like the test suite to use the discriminated union, only dealing with integers regarding the score.

The suggested discriminated union is great, although I think I would prefer it if the stub implementation only contained the type definition:

```fsharp
type DieValue =
  | One
  | Two
  | Three
  | Four
  | Five
  | Six
```

So without the added `Value` member. That is then something that the student can figure out on their own. Obviously the example implementation could use that member definition.

**Comment by spencerwi** [comment]
Cool, I'm getting started on this. How does one actually run the generator that generates the tests? I want to make sure my changes to the test won't just get overwritten (or will get correctly overwritten).

**Comment by ErikSchierboom** [comment]
Well, you don't manually edit the test suite, as running the test generator would indeed overwrite the changes, but you modify the generator itself to output the correct values! You can find the generators code [here](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs#L1496), and documentation on how to write/customize a generator can be found [here](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md).

Once you have made changes to the generator, you can run it by opening a command prompty in the `generators` directory and running: `dotnet run -e yacht`. This will use the generator to regenerate the test suite. 

The next step is to convert the `Example.fs` and `Yacht.fs` files to conform to use/defined the new discriminated union.

Finally, please make sure that the example implementation passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=yacht` or `.\build.ps1 -Exercise yacht`, depending on your operating system.

**Comment by spencerwi** [comment]
Awesome, that's what I was looking for. Thanks!
