### ISSUE TITLE
Allow generator to output outdated exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#581]
It would be quite useful if the generator would allow for displaying the exercises that have a test suite that is based on an outdated version of the canonical data.

To list these outdated exercises, one should be able to do `dotnet run -s Outdated`.

The generators code can be found [here](https://github.com/exercism/fsharp/tree/master/generators), and the documentation can be found [here](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md).

**Comment by jrr** [comment]
It seems a little tricky to make this work like the other statuses.

Skimming through the code, it looks like the behavior of `-s` is:

1) Filter down the set of exercises to those that match the selected status.
2) Iterate through the exercises and depending on the status, either generate code or log a message.
(`Implemented` status gets generated, and `Unimplemented|MissingData|Deprecated|Custom` all log messages but don't run generators)

Would an outdated exercise be both _Implemented_ and _Outdated_? How would I adapt the [regenerateTestClass](https://github.com/exercism/fsharp/blob/ef418e0b0e9efd085adb78dc030910d244205cc5/generators/Program.fs#L27-L43) function?

I see a couple other options:

#### 1) Add a verb

It seems like the current generator has an implied verb of "generate", and we want another verb. "show"? "list"?

We could use [the library's support for verbs](https://github.com/commandlineparser/commandline/wiki#verbs), so we'd have commands like `dotnet run -- generate -e binary-search` or `dotnet run -- show -s outdated`. It might be possible to have a default verb so you get _generate_ if you don't specify one.

A downside here is that I think it'd require the extra `--` after `dotnet run`, where today we can mostly get by without using it.

#### 2) Add a separate argument/flag

E.g. `dotnet run --outdated` / `dotnet run -o`

This seems a lot easier, and I already have it working on a branch ;)

**Comment by ErikSchierboom** [comment]
I would be fine with throwing an error.
