### ISSUE TITLE
Implement new exercise: affine-cipher

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#582]
There is a new exercise, [affine-cipher](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/description.md), which data can be found here: https://github.com/exercism/problem-specifications/tree/master/exercises/affine-cipher

To implement the `affine-cipher` exercise, the following needs to be done:

- Create a directory for the new exercise in the `exercises` directory (note: this has to match the exact exercise name).
- Add a new entry to the [config.json](https://github.com/exercism/fsharp/blob/master/config.json) file.
- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md).
- Create a stub implementation file that contains the code necessary to compile (which are the methods called by the test file), but lacks an implementation. (see [this example](https://github.com/exercism/fsharp/blob/master/exercises/two-fer/TwoFer.fs)).
- Create an implementation file that passes all the tests.
- Create a project file for the project (you can probably best copy and modify one of the existing projects).

**Comment by ErikSchierboom** [comment]
There are no such instructions at the moment, but I can answer those:

> Is affine-cipher a core exercise?
No.

> What topics should be added?
Ehm, it depends on what the exercise is teaching the student. In this case, I think I would look for inspiration at similar, cipher related exercises.

> Is it unlocked by anything?
Yes, being non-core means that it has to be unlocked. This will depend on the difficulty and the topics involved, so we can look into this once there is a PR.

> what is the difficulty level?
This is basically a judgement call. I can help you with this once I see the example implementation.

**Comment by bob0the0mighty** [comment]
Thanks

**Comment by ErikSchierboom** [comment]
@bob0the0mighty Are you working on this?

**Comment by bob0the0mighty** [comment]
I had most of this but got hung up on the example and forgot about it. Give me another 24 hours to get something. In the meantime I can make a PR with the other parts if that'd help?

**Comment by ErikSchierboom** [comment]
@bob0the0mighty That would definitely be useful! If you start the PR's title with WIP, we won't even be  able to merge it until that it removed.

As for the example implementation, you could look at my [C# implementation](https://github.com/ErikSchierboom/exercism/blob/master/csharp/affine-cipher/AffineCipher.cs) for inspiration. Note that an example implementation doesn't have to be the prettiest of code; its goal is to verify that it is possible to solve the test suite.

**Comment by davidelettieri** [comment]
@bob0the0mighty are you planning to work on this? If not I will pick up the issue :)

**Comment by bob0the0mighty** [comment]
Life happened and I forgot about this. Feel free pick it up.
