### ISSUE TITLE
Add generator for exercise: grade-school

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#586]
The [grade-school](https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/description.md) now has [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json). We should replace the existing, manually crafted test suite with on that is automatically generated based on the canonical data.

To implement a generator for the `grade-school` exercise, the following needs to be done:

- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md).
- Make sure the implementation file passes all the tests (hint: you can verify this by running `./build.sh --exercise=grade-school` or `.\build.ps1 -Exercise grade-school`.

**Comment by MaritimeMartin** [comment]
The current F# solution uses `type School = Map<int, string list>` in the GradeSchool.fs (but not in the example file, thought). Nevertheless, the canonical data uses a list of lists which could be represented by a` string*int list`. 

I like the School type because it's more domain specific. So I would go this way. I think F# trainees should learn that way to code as soon as possible.

**Comment by ErikSchierboom** [comment]
I agree. I think this is a nice exercise to learn about maps.

**Comment by MaritimeMartin** [comment]
I am failing with casting this `[["Blair", 2], ["James", 2], ["Paul", 2]]` to a List<string*int>. Could somebody help?

**Comment by ErikSchierboom** [comment]
That's because `[["Blair", 2], ["James", 2], ["Paul", 2]]` is not a `string*int list`, but a `string*int list list`.

**Comment by MaritimeMartin** [comment]
I'll use a helper function with RenderSetup to fill the school.

**Comment by ErikSchierboom** [comment]
Closed by #652.
