### ISSUE TITLE
Update test suite for exercise: queen-attack

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#593]
The `queen-attack` exercise's [test suite](https://github.com/exercism/fsharp/blob/master/exercises/queen-attack/QueenAttackTest.fs) is automatically generated using its [test generator](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs). This test generator converts the `queen-attack`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/queen-attack/canonical-data.json) into the test suite just mentioned.

The canonical data for the `queen-attack` exercise has been updated since the test suite was last generated. We should be updating thetest suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e queen-attack`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/fsharp/blob/master/exercises/queen-attack/Example.fs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=queen-attack` or `.\build.ps1 -Exercise queen-attack`, depending on your operating system.

**Comment by nemesv** [comment]
I'm started to work on this one.

**Comment by nemesv** [comment]
I only updated the generator but did not change the tests.

However I've  noticed that the `create: int * int -> unit` function does not do any error handling.

Should we consider to except some error handling (e.g. returning `Result<int * int, string> or throwing exception in the tests?

**Comment by ErikSchierboom** [comment]
> However I've noticed that the create: int * int -> bool function does not do any error handling.

Ehm, we check the boolean return value in the tests: https://github.com/exercism/fsharp/blob/7788c6c767a18b9b9c6962e201787462ac8f911b/exercises/queen-attack/QueenAttackTest.fs#L12 So I would consider that to be our error handling logic.
