### ISSUE TITLE
Update test suite for exercise: change

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#596]
The `change` exercise's [test suite](https://github.com/exercism/fsharp/blob/master/exercises/change/ChangeTest.fs) is automatically generated using its [test generator](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs). This test generator converts the `change`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/change/canonical-data.json) into the test suite just mentioned.

The canonical data for the `change` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e change`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/fsharp/blob/master/exercises/change/Example.fs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=change` or `.\build.ps1 -Exercise change`, depending on your operating system.

**Comment by Ishaan28malik** [comment]
can i do this one ?
please help me how to do it or brief me out ..

**Comment by ErikSchierboom** [comment]
You can take it! The how to is specified in the comments above.

**Comment by Ishaan28malik** [comment]
ok thanks do i need to forkedit and then PR ?

**Comment by ErikSchierboom** [comment]
Correct.

**Comment by Ishaan28malik** [comment]
ok so i am starting with it 
is it for us or it's your own issue that u will solve yourself ?

**Comment by Ishaan28malik** [comment]
as i am starting with it ..

**Comment by Ishaan28malik** [comment]
no issues i am doing my thing just wait.

**Comment by Ishaan28malik** [comment]
No sorry I actually switched my project
But soon I will work on some of the two I will let u know

**Comment by Ishaan28malik** [comment]
I actually tried bt failed to do it @ErikSchierboom
