### ISSUE TITLE
Update test suite for exercise: grains

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#597]
The `grains` exercise's [test suite](https://github.com/exercism/fsharp/blob/master/exercises/grains/GrainsTest.fs) is automatically generated using its [test generator](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs). This test generator converts the `grains`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/canonical-data.json) into the test suite just mentioned.

The canonical data for the `grains` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e grains`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/fsharp/blob/master/exercises/grains/Example.fs) passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=grains` or `.\build.ps1 -Exercise grains`, depending on your operating system.

**Comment by MaritimeMartin** [comment]
I run `dotnet run -e grains` but nothing changed on the test file. I am not sure if this is good or bad.

**Comment by ErikSchierboom** [comment]
Are you sure? I expect the test generator to crash based on this change: https://github.com/exercism/problem-specifications/commit/2ec42ab21ff9d3b72ea907457f257073824cb97e

Can you post the console output?

**Comment by MaritimeMartin** [comment]
Those changes are already considered in the [test file](https://github.com/exercism/fsharp/blob/master/exercises/grains/GrainsTest.fs)

**Comment by ErikSchierboom** [comment]
> but nothing changed on the test file

If I run the specified command, the tests don't change, but the version number does. I'd be perfectly happy with a PR with just a version update.

**Comment by ErikSchierboom** [comment]
Note: the problem has been located! The instructions forgot to mention that you have to run the dotnet command in the `generators` directory. Sorry about that.

**Comment by MaritimeMartin** [comment]
I am on it. Looks like it has to do with the fact that I am working on Ubuntu. I'll switch to MS

**Comment by MaritimeMartin** [comment]
I fixed all issures related to my dev environment. After I run `.\build.ps1 -Exercise grains` I found some issues in the Generators.fs file:

`override __.RenderExpected (_, _, value) = 
        match string value with
        | "-1" -> "Error \"Invalid input\""
        | x    -> sprintf "Ok %sUL" x`

The new Version of the canonical data has a much more detailed error message. I am on it and will solve it tomorrow.

**Comment by ErikSchierboom** [comment]
> The new version of the canonical data has a much more detailed error message. I am on it and will solve it tomorrow.

Sounds good!
