### ISSUE TITLE
Update test suite for exercise: bob

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#604]
The `bob` exercise's [test suite](https://github.com/exercism/fsharp/blob/master/exercises/bob/BobTest.fs) is automatically generated using its [test generator](https://github.com/exercism/fsharp/blob/master/generators/Generators.fs). This test generator converts the `bob`'s [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json) into the testsuite just mentioned.

The canonical data for the `bob` exercise has been updated since the test suite was last generated. We should be updating the test suite to the latest version. To do this, one should:
- Run the test generator for the exercise. This is done by opening a command prompt in the `generators` directory and running: `dotnet run -e bob`.
- At this point, you should check to see what the updated test suite looks like. There are basically two options: one, the test generator was compatible with the updated canonical data and the test suite was updated and still has the same structure. The second option is that the test generator could not process the changed canonical data, in which case the generator has to be modified. In that case, you should check out the [generator docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md) in which the generators setup is explained in detail.
- Finally, please make sure that the [example implementation](https://github.com/exercism/fsharp/blob/master/exercises/bob/Example.fs)passes all the tests. You can verify this by opening a command prompt in the root directory and running `./build.sh --exercise=bob` or`.\build.ps1 -Exercise bob`, depending on your operating system.

**Comment by jkaan** [comment]
I would like to take this one if that's okay :).

**Comment by ErikSchierboom** [comment]
Sure!

**Comment by jkaan** [comment]
Once I run the `dotnet run -e bob` in the generators folder I get this error message:

Do you know what that could be?

![image](https://user-images.githubusercontent.com/3824068/46368357-4e812480-c680-11e8-9b6b-3b5e42001734.png)

**Comment by ErikSchierboom** [comment]
Well that's odd! I have never had that problem. On which system are you running the code?

**Comment by jkaan** [comment]
A Mac. Dotnet version 2.1.402

**Comment by ErikSchierboom** [comment]
Hmmm, I also have a Mac. I can test it later. Which MacOS version?

**Comment by jkaan** [comment]
Mojave, could that be it?

**Comment by ErikSchierboom** [comment]
Could be! Could you see if there are packages you can update?

**Comment by jkaan** [comment]
@ErikSchierboom What packages are you referring to? I'm quite new to C# so :).

**Comment by jkaan** [comment]
@ErikSchierboom If I update all the packages then I still get the same message.

**Comment by ErikSchierboom** [comment]
Have you tried googling for the error?

**Comment by ErikSchierboom** [comment]
I've looked into this a bit, and it is a really odd problem that I have never seen. It is not Mojave I think, as my Mac also runs Mojave and it works there.

With some Googling, I found some issues that seem related: 

- https://github.com/JuliaLang/julia/issues/16009#issuecomment-213594382
- https://github.com/Vector35/binaryninja-api/issues/823
- https://github.com/GitTools/GitVersion/issues/436

Looking into this issues, it appears to be some Git configuration error locally, although I can't exactly pinpoint what it is.

If you look at the code, you can [see](https://github.com/exercism/fsharp/blob/master/generators/CanonicalData.fs#L35) that it tries to `git clone` this URL: https://github.com/exercism/fsharp/blob/master/generators/CanonicalData.fs#L24. Maybe you could check to see if you can do a git clone of that repository on the command-line?

**Comment by ErikSchierboom** [comment]
Coudl you perhaps also show the command-line output?

**Comment by jkaan** [comment]
@ErikSchierboom I haven't tested it yet, I'm going to do that; reading the first issue (comment) that you linked, that's probably it. I also have a global config that changes all `https` routes to `git...` so that must be causing it.

**Comment by ErikSchierboom** [comment]
Great! Good to hear!
