### ISSUE TITLE
CI: build generators project

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#640]
We should verify that the [generators project](https://github.com/exercism/fsharp/blob/master/generators/Generators.fsproj) builds successfully in our [build script](https://github.com/exercism/fsharp/blob/master/build.cake). 

For inspiration, the C# track [already does this](https://github.com/exercism/csharp/blob/master/build.cake#L87), although we should actually build the generators project before running the tests.

**Comment by roman-shuhov** [comment]
working on it

**Comment by ErikSchierboom** [comment]
Closed by #645.
