### ISSUE TITLE
XUnit 2.4.0 needs to be used in exercism fsproj files to support running tests within Jetbrains Rider IDE 

### ISSUE THREAD

**Issue by lestephane** [exercism/fsharp#641]
When loading the fsproj of an exercism exercise, i was unable to run the tests within the Rider IDE
I followed up with [an issue filed on their side](https://youtrack.jetbrains.com/issue/RIDER-17461).

They in turn pointed to [an issue with XUnit](https://github.com/xunit/xunit/issues/1588) that was fixed in 2.4.0.

I verified the fix by using XUnit 2.4.0 in one exercism (Leap.fsproj)
```bash
$ cat Leap.fsproj | grep 2.4.0
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.4.0" />
```

And was able to run the tests from within the IDE.

Can 2.4.0 be used in fsproj files?

**Comment by ErikSchierboom** [comment]
Sure! Would you be willing to create a PR?

**Comment by lestephane** [comment]
The PR is on its way, the command i used (for future reference) is:

```bash
find -name "*fsproj" | xargs sed -i -e "s/\"2\.3\.1\"/\"2.4.0\"/g"
```
Maybe the fsproj _standard_ dependencies should be defined in one place going forward, and some sort of include or placeholder expansion be used to generate the final fsproj that lands on the user's machine.

**Comment by ErikSchierboom** [comment]
I understand the idea, but in practice this is not really a problem, as changing version numbers doesn't happen that often and a simple search and replace is often enough. Thanks for doing this!
