### ISSUE TITLE
Check example implementation file' performance

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#642]
It might be interesting to do some type of performance analysis of the example implementations, to see where the bottlenecks are (if there are any). For example, if one test runs for 1,5 minute, it can significantly slow down the entire build.

**Comment by ErikSchierboom** [comment]
Note that for the C# track, there was a PR that improved the performance of two notoriously slow exercises: `alphametics` and `largest-series-product`: https://github.com/exercism/csharp/pull/719.

**Comment by davidelettieri** [comment]
I'll work on this if that's ok, I'll already noticed in the travis logs a group of tests that take ~1 min to run, I'll investigate further and get back with more info.

**Comment by ErikSchierboom** [comment]
Sure! I've done a similar PR in the C# track. You could look for inspiration there (I'm on mobile hence no link)

**Comment by robkeim** [comment]
I believe this is the PR @ErikSchierboom was looking for:
https://github.com/exercism/csharp/pull/719

**Comment by ErikSchierboom** [comment]
Yes that's the PR I was referring to! Thanks @robkeim!
