### ISSUE TITLE
Update test suite for exercise: Allergies

### ISSUE THREAD

**Issue by roman-shuhov** [exercism/fsharp#647]
I noticed that multiple tests got updates in canonical data and some tests changed. This ticket is to update canonical data for Allergies exercise. 

Here is a full list of changed issues:
- allergies
- alphametics
- anagram
- atbash cipher
- bracket push 
- change
- grep
- largest series product
- leap
- pangram
- protein translation
- rna transcription
- robot simulator
- saddle points
- scale generator
- sum of multiples
- triangle
- twelve days

**Comment by ErikSchierboom** [comment]
Closed by #648.
