### ISSUE TITLE
"<!-- raw HTML omitted -->" appears in exercise Readme

### ISSUE THREAD

**Issue by jrr** [exercism/fsharp#666]
I noticed today that the the online Readme for F#'s "grep" exercise was missing some code blocks, replaced instead with "`<!-- raw HTML omitted -->`":

https://exercism.io/my/solutions/acbfdc0c76bb4140af8c2d3c25bba422

For reference, here's the markdown source:

https://github.com/exercism/fsharp/blob/master/exercises/grep/README.md

Hopefully this is a lingering symptom of an old problem, and something just needs to be regenerated. How are exercise readmes rendered?

**Comment by jrr** [comment]
@iHiD I haven't submitted a solution for this one.

**Comment by ErikSchierboom** [comment]
@jrr This was fixed  in yesterday's docs PR: https://github.com/exercism/fsharp/commit/0f1a148b2d3285bb3367a726fbfbcb1fa18f413b#diff-ec64751c1e733a62d02193e7db61a00dR23
