### ISSUE TITLE
Implement new exercise: dnd-character

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#667]
There is a new exercise, [dnd-character](https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/description.md), which data can be found here: https://github.com/exercism/problem-specifications/tree/master/exercises/dnd-character

To implement the `dnd-character` exercise, the following needs to be done:

- Create a directory for the new exercise in the `exercises` directory (note: this has to match the exact exercise name).
- Add a new entry to the [config.json](https://github.com/exercism/fsharp/blob/master/config.json) file.
- Create a generator to automatically convert the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/canonical-data.json) to a test file. For more information on how to do this, check the [generators docs](https://github.com/exercism/fsharp/blob/master/docs/GENERATORS.md).
- Create a stub implementation file that contains the code necessary to compile (which are the methods called by the test file), but lacks an implementation. (see [this example](https://github.com/exercism/fsharp/blob/master/exercises/two-fer/TwoFer.cs)).
- Create an implementation file that passes all the tests.
- Create a project file for the project (you can probably best copy and modify one of the existing projects).

Note that this exercise should be implemented using property-based tests where possible. An example of an existing exercises that uses property-based tests is the [diamond](https://github.com/exercism/fsharp/blob/master/exercises/diamond/DiamondTest.fs) exercise.

**Comment by davidelettieri** [comment]
I'll work on this if that's ok

**Comment by ErikSchierboom** [comment]
Sure! You can look at the [C# equivalent PR](https://github.com/exercism/csharp/pull/736) to get inspiration for how to implement this. As an alternative, you could look at the equivalent [Haskell PR](https://github.com/exercism/haskell/pull/782), which ties directly into a specific property-generator framework (which should be FsCheck in our case). I'm fine with either option, so feel free to choose whatever you feel works best.
