### ISSUE TITLE
Use decimal type for money related exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#670]
Any exercises related to money should use the `decimal` type instead of `double`or `float` (see [this page](https://stackoverflow.com/questions/693372/what-is-the-best-data-type-to-use-for-money-in-c). Out of the top of my head, these exercises will include (but there may be more):

- book-store
- bank-account

**Comment by davidelettieri** [comment]
I checked the exercise in the repository and it seems to me that only 

- book-store
- bank-account
- rest-api

deal with money. Only bank-account need to be updated to use `decimal`

**Comment by ErikSchierboom** [comment]
Alright, thanks for looking into this!

**Comment by davidelettieri** [comment]
Actually bank-account is using decimals already we can close this issue

**Comment by ErikSchierboom** [comment]
Great!
