### ISSUE TITLE
FSharp learning page has a broken link

### ISSUE THREAD

**Issue by baschou** [exercism/fsharp#680]
In this page: http://www.exercism.io/languages/fsharp/resources
The web site http://www.tryfsharp.org/ seems not working anymore

**Comment by ErikSchierboom** [comment]
Good catch. Perhaps we can replace that reference to the https://dotnet.microsoft.com/learn/languages/fsharp-hello-world-tutorial/intro page. Would you be willing to create a PR for that? The document that needs to be edited can be found [here](https://github.com/exercism/fsharp/blob/master/docs/LEARNING.md).

**Comment by ErikSchierboom** [comment]
A [PR](#695) has been created.
