### ISSUE TITLE
Add script to get started with implementing a new exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#697]
We have a [GitHub template](https://github.com/exercism/fsharp/blob/master/.github/ISSUE_TEMPLATE/new_exercise.md) that describes the steps to implement a new exercise. We should create a script to automate these steps where possible.

**Comment by davidelettieri** [comment]
@ErikSchierboom I got a 404 trying to access the template. Am I missing something?

**Comment by robkeim** [comment]
@ErikSchierboom do we have a template for the F# track yet?

@davidelettieri here's the template for the C# track (which should be similar to what is required for a new exercise in the F# track):
https://github.com/exercism/csharp/blob/master/.github/ISSUE_TEMPLATE/new_exercise.md

**Comment by ErikSchierboom** [comment]
@robkeim Ah no, not yet. There is an open issue for that: https://github.com/exercism/fsharp/issues/673

**Comment by davidelettieri** [comment]
Thanks @ErikSchierboom for the work on the issue template, I'll work on the script if that's ok :)

**Comment by ErikSchierboom** [comment]
Absolutely!
