### ISSUE TITLE
Fix test generators

### ISSUE THREAD

**Issue by robkeim** [exercism/fsharp#715]
The following test generators are currently not working:
- [x] Allergies
- [ ] Palindrome (canonical data change [here](https://github.com/exercism/problem-specifications/commit/fbb30474df21e5de259493b010d5c502c049fa40#diff-11b95c88ab2f41a69599edd346658107))

**Comment by davidelettieri** [comment]
I'm working on the palindrome exercise

**Comment by davidelettieri** [comment]
I'm hitting some issue and waiting for a response in https://github.com/fsprojects/FsUnit/issues/130

**Comment by ErikSchierboom** [comment]
This is likely due to FsUnit not being able to correctly infer the type. You could check to see if adding an explicit type annotation helps. See e.g. https://github.com/exercism/fsharp/blob/master/generators/Generators.fs#L1032

**Comment by davidelettieri** [comment]
That works thank Erik!

**Comment by robkeim** [comment]
Thanks @davidelettieri for taking this issue!
