### ISSUE TITLE
Benchmarking for the Tree Building exercise

### ISSUE THREAD

**Issue by TeaDrivenDev** [exercism/fsharp#736]
I'm working on improving my ability to mentor the Tree Building exercise, and the instructions mention the "slow" original code, which seems to imply that improved performance is one of the goals (they don't say any more about that, though). I have set up benchmarking for myself using BenchmarkDotNet to be able to compare a given solution with the original code, as well as a very fast implementation. I wonder if it makes sense to try to bring that to the users "in the box" with the exercise (minus the fast solution), so they can see for themselves how they're doing, as they can with the unit tests.

It would mean adding another dependency and making the project more complex than the others; also, an easy way for the user to run the benchmarks would have to be determined.

**Comment by ErikSchierboom** [comment]
Great issue! There are several things here:

1. I'm not sure the original code is actually slow. Maybe we should be making it slow, especially if it is in the instructions. Did you check to see if the original code is indeed slow? If it isn't very slow, maybe we should make it slower :)
1. We don't teach users about libraries, but the performance suggestion should be approached by using `BenchmarkDotNet`, I agree.
1. The `tree-building` exercise is actually quite hard for both students and mentors. It might make sense to remove it as a core exercise and make it a side exercise. If we do this, I then also don't mind adding the additional `BenchmarkDotNet` dependency.

What do you think?

**Comment by TeaDrivenDev** [comment]
Well, it's not extremely slow, but slow enough that performance improvements are possible without huge amounts of in-depth F# knowledge; many solutions seem to be at least somewhat better, just from writing more sensible code (some are also a lot slower, though). The fastest one I've seen is currently my own, after taking some hints from the previously fastest and then specifically tuning for speed; I get a 64% performance improvement over the original code, using all the unit test cases as the benchmark set. 

There may be ways to make the original code even slower, but what I've tried without making it too contrived or rewriting it only added about 10% to the running time.

I also agree that it's a difficult exercise for both sides, mostly due to its open-endedness. Removing/replacing it as a core exercise sounds like a good idea.

**Comment by TeaDrivenDev** [comment]
Closing this, as it has been implemented.
