### ISSUE TITLE
Non-continuous is actually continuous

### ISSUE THREAD

**Issue by zlatozar** [exercism/fsharp#757]
https://github.com/exercism/fsharp/blob/5a8d96a849e546e361601769e639fc09fbcb0a52/exercises/tree-building/TreeBuildingTest.fs#L189

This records set creates a tree: **Branch** (0, [**Leaf** 1; **Branch** (2, [**Leaf** 4])])
```
0
|  \
1   2
    |
    4
```

**Comment by ErikSchierboom** [comment]
I agree that the description is not good. What this test tries to verify is the following rule as specified in the README:

> The ID number is always between 0 (inclusive) and the length of the record list (exclusive)

The list for this case has a length of `4`, so there should not be an ID equal to `4`. Perhaps you could come up with a more descriptive name?

**Comment by zlatozar** [comment]
Thanks @ErikSchierboom. Something like "Out of bound record id" could do the job

**Comment by ErikSchierboom** [comment]
@zlatozar Would you perhaps be interested in submitting a PR?
