### ISSUE TITLE
"D&D Character" requires using a class

### ISSUE THREAD

**Issue by TeaDrivenDev** [exercism/fsharp#764]
The solution stub for the "D&D Character" exercise contains a class for the type to be implemented, and the unit tests directly call the constructor, which leaves the student no option than to actually solve this using a class. This is not preferred in F#, though, and there's no good reason why using a class would make sense here in any way.

The tests should just call a creation function here and not prescribe an implementation. I'm not sure what to do about the solution stub, though.

**Comment by ErikSchierboom** [comment]
> The tests should just call a creation function here

Agreed.

> I'm not sure what to do about the solution stub, though.

One option is to replace all the direct property accessors by functions, similar to how the [`robot-name` stub does this](https://github.com/exercism/fsharp/blob/master/exercises/robot-name/RobotName.fs). What do you think about that approach?

**Comment by davidelettieri** [comment]
I can work on this issue if needed, I was the one doing the first implementation and I would be happy to fix it if no one else does.

**Comment by ErikSchierboom** [comment]
@davidelettieri That would be brilliant! I don't see it as the first implementation needing fixing BTW, it's just a refinement of the exercise.

**Comment by TeaDrivenDev** [comment]
I'm not sure about this approach, as that would add quite a few functions that are only used for testing and would not exist in "real-world" code. What about having a `create` function, but still accessing the fields/properties directly? That would cause the initial project not to compile, but [`space-age`](https://github.com/exercism/fsharp/blob/master/exercises/space-age/SpaceAge.fs) for example also does this - the tests reference identifiers that don't exist initially, but will run fine with either the typical solution using a DU, or for example one that uses static instances of a record type that are named appropriately.

**Comment by ErikSchierboom** [comment]
I'm fine with either option. Let's go with the suggestion of @TeaDrivenDev, as that will also require the least amount of change.
