### ISSUE TITLE
Fix failing builds

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#777]
Builds have been failing of late, which is due to the configlet tool not being able to be downloaded. One workaround would be to retry, as the problem seems to be intermittent.

**Comment by robkeim** [comment]
We should try to come up with a similar solution to C#. Here's the corresponding C# issue where discussion has started on how to do this:
https://github.com/exercism/csharp/issues/1367

**Comment by robkeim** [comment]
Here's a temporary workaround:
https://github.com/exercism/fsharp/pull/781
