### ISSUE TITLE
Sync tests in update-canonical-data.ps1 script

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#824]
The `update-canonical-data.ps1` script should be updated to use the [`canonical_data_syncer`](https://github.com/exercism/canonical-data-syncer) to update the `tests.toml` files.

Depends on #822

**Comment by ErikSchierboom** [comment]
The `canonical-data-syncer` functionality has been moved to `configlet`. The canonical data should now be updated running `configlet sync`.

**Comment by 64J0** [comment]
This file is not available in this repository, at least I have not found it here.

Should this issue be kept open?

Maybe it's better to transfer it to another repository.
