### ISSUE TITLE
F# queue clogged? No mentor feedback for two months or so.

### ISSUE THREAD

**Issue by aage** [exercism/fsharp#835]
I've submitted a solution to the **Space Age** problem a while ago but haven't received any mentor feedback.

I would like to move on with the main exercises.

**Comment by aage** [comment]
Hi Erik,

Thank you for your response.

I will be more patient and focus on side quests :)
I absolutely appreciate everyone's work on exercism, it is a great thing and helps me get better at F#.

Cheers

**Comment by ErikSchierboom** [comment]
Good to hear!
