### ISSUE TITLE
[v3] Unused link in hints.md of pattern-matching exercise

### ISSUE THREAD

**Issue by aimorris** [exercism/fsharp#847]
https://github.com/exercism/v3/blame/master/languages/fsharp/exercises/concept/pattern-matching/.docs/hints.md#L23

This link is defined but not used anywhere within the file.

**Comment by aage** [comment]
Is this issue still relevant? There doesn't seem to be a `pattern-matching` dir within `exercises/concept`.

**Comment by ErikSchierboom** [comment]
Nope. This is no longer relevant.
