### ISSUE TITLE
Improve Concept Exercise: strings

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#848]
## Goal

The [`introduction.md` document of the `strings` exercise](https://github.com/exercism/v3/blob/master/languages/fsharp/exercises/concept/strings/.docs/introduction.md) does not introduce the syntax needed to concatenate strings, which the student _does_ need to do. An short explanation and syntax example should be added to the `introduction.md` document on how to use the `+` operator or `sprintf` to format strings. The contents for this can be extracted from the [`after.md` document](https://github.com/exercism/v3/blob/master/languages/fsharp/exercises/concept/strings/.docs/after.md).

## Help

If you have any questions while improving the exercise, please post the questions as comments in this issue.

**Comment by aage** [comment]
Is this issue still relevant? The links result in a HTTP 404.

**Comment by ErikSchierboom** [comment]
Yes, this is still relevant! The documents that need to be updated are:

- https://github.com/exercism/fsharp/blob/main/exercises/concept/log-levels/.docs/introduction.md
- https://github.com/exercism/fsharp/blob/main/concepts/strings/introduction.md

**Comment by aage** [comment]
@ErikSchierboom I've added a PR (https://github.com/exercism/fsharp/pull/1025) that would add examples for the `+` operator and `sprintf` function. I've improvised this documentation, since you specifically mention the `sprintf` function and no example of that could be found here: https://github.com/exercism/fsharp/blob/main/concepts/strings/about.md

**Comment by ErikSchierboom** [comment]
Great, thanks!

**Comment by aage** [comment]
@ErikSchierboom This issue can be closed right? Since the PR is merged into main.
