### ISSUE TITLE
Incorrect test in bank-account for functional approaches

### ISSUE THREAD

**Issue by ryepesg** [exercism/fsharp#905]
The following test in `bank-account` encourages the use of mutable variables instead of allowing a functional approach. 

```fsharp
let ``Balance can increment or decrement`` () =    
    let account = mkBankAccount() |> openAccount
    let openingBalance = account |> getBalance 

    let addedBalance = 
        account 
        |> updateBalance 10.0m
        |> getBalance

    let subtractedBalance = 
        account 
        |> updateBalance -15.0m
        |> getBalance

    openingBalance |> should equal (Some 0.0m)
    addedBalance |> should equal (Some 10.0m)
    subtractedBalance |> should equal (Some -5.0m)
```

The problem is `subtractedBalance` being calculated using `account` instead of the version where the balance was updated already. An example of how to fix it is by introducing the `addedBalanceAccount` binding:

```fsharp
...
    let addedBalanceAccount = 
        account 
        |> updateBalance 10.0m

    let addedBalance = 
        addedBalanceAccount
        |> getBalance

    let subtractedBalance = 
        addedBalanceAccount
        |> updateBalance -15.0m
        |> getBalance
...
```

**Comment by ErikSchierboom** [comment]
That's true, but for this exercise we actually _want_ to have users practice using mutable values. This might not be the default behavior in F#, but it does have its place. This exercise thus is intended to help teach that. See https://github.com/exercism/fsharp/blob/main/exercises/practice/bank-account/.meta/Example.fs

**Comment by ryepesg** [comment]
Thanks for the explanation Erik. I will close the issue since I see it is by design.

**Comment by ErikSchierboom** [comment]
Sure!
