### ISSUE TITLE
Add support to .NET Core 5.0

### ISSUE THREAD

**Issue by rslopes** [exercism/fsharp#920]
Running the tests locally results in the following warning:

```
warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future.
```

Not sure if this is already solved for F# track on V3.

Reference: exercism/csharp#1439

**Comment by ErikSchierboom** [comment]
Yes, all the V# exercises will be using .NET 5: https://github.com/exercism/fsharp/blob/main/exercises/practice/affine-cipher/AffineCipher.fsproj#L3 :)
