### ISSUE TITLE
update-exercise-tools.ps1 writing tool manifest to wrong directories

### ISSUE THREAD

**Issue by rdipardo** [exercism/fsharp#959]
The `update-exercise-tools` script doesn't work as intended.

Instead of writing a tool manifest to every exercise directory, it stops after hitting 3 top-level directories, none of which contains a .NET project:

![1st_2021-08-02_02-15-40](https://user-images.githubusercontent.com/59004801/128408565-b69c11e3-73e3-41fc-8ba6-dfdcc7be03d7.png)

If run a second time, it will exit with a failure code once it finds an existing manifest:

![2nd_2021-08-02_02-17-04](https://user-images.githubusercontent.com/59004801/128408657-94fc06a6-e546-4b1f-a08a-535603e085c4.png)

On the face of it, I'd say the directory searching logic needs to be more recursive (to find all the excercises) and more selective (to put manifests only where they belong).

**Comment by ErikSchierboom** [comment]
Yeah, this is a result of us transitioning to the v3 structure where we now have exercises in `exercises/concept` and `exercises/practice`. Would you be interested in submitted a PR to fix this?
