### ISSUE TITLE
Tests missing attributes

### ISSUE THREAD

**Issue by galambborong** [exercism/fsharp#970]
The test files (that I've checked, it may not apply to all) are currently missing their `[<Fact>]` attributes, so are essentially unavailable to the online test runner. So far as I can tell, the user cannot edit these. 

Please see the following three screenshots: 

The standard `hello-world`:
![hello-world-f-sharp-error](https://user-images.githubusercontent.com/57960614/131736789-bd44e815-8ccf-43de-917a-7bc0214fcb9f.png)

The second for the `phone-number` exercise
![phone-number-f-sharp-error](https://user-images.githubusercontent.com/57960614/131736825-c666bc4a-845e-48ea-9cb9-4847542adc2b.png)

I reproduced this locally:
![rider-f-sharp-error](https://user-images.githubusercontent.com/57960614/131736972-c27a117e-6dc3-4f55-8a1a-2ed26ebc937e.png)

With `[<Fact>]` reinstated, the tests are available:
![rider-f-sharp-pass](https://user-images.githubusercontent.com/57960614/131737225-8426a159-92ab-457d-9cb6-7ef94b82b48e.png)

Well done and thank you to all involved in the new version 3 of Exercism!

**Comment by ErikSchierboom** [comment]
@galambborong Weird. I think it's some client-side issue actually, as downloading the exercise via the CLI using `exercism download --track fsharp --exercise phone-number` will download everything just fine. I'll look into it.

**Comment by galambborong** [comment]
Yes, I should have mentioned that the local exercise files are fine (I just deleted the attribute locally to reproduce what was happening online), so this seems isolated to the online test runner. Thank you @ErikSchierboom!

**Comment by ErikSchierboom** [comment]
I have a hunch that it has something to do with the `<` and `>` characters not being escaped.
