### ISSUE TITLE
Booking up for beauty exercise testing online problem

### ISSUE THREAD

**Issue by celldee** [exercism/fsharp#975]
The 'Booking up for Beauty' exercise tests pass when I work locally by downloading to my machine. However, the tests fail when I submit my solution or run my solution in the online editor.

I am not sure what's happening because I can't see which tests are failing online.

**Comment by ErikSchierboom** [comment]
I know the issue, I've just not found the time to fix it yet. I'll keep you updated!

**Comment by celldee** [comment]
No problem. Thanks for your efforts. If I can help in any way let me know.
