### ISSUE TITLE
Unsufficient explanation in "Interest is Interesting" exercise

### ISSUE THREAD

**Issue by b47on** [exercism/fsharp#983]
The instructions for the exercise (Interest is Interesting: https://exercism.org/tracks/fsharp/exercises/interest-is-interesting)
states in task 3:

> 3. Calculate how much money to donate
> Implement the amountToDonate function to calculate how much money to donate to charities based on the balance and the tax-free percentage that the government allows:
> 
> let balance = 550.5m
> let taxFreePercentage = 2.5
> amountToDonate balance taxFreePercentage
> // => 27
> Note that the value returned is an int.

But there is no information (domain knowledge) how one is supposed to calculate the donation ammount. 
What is  tax free percentage and why donation dependens on it?

Tried to google it but could not find any explanation. 
I think more information should be given.

**Comment by ErikSchierboom** [comment]
The instructions contain the following section:

> Each year the government allows you donate a percentage of your money to charity, tax free. Because you're a nice person, if your balance is positive at the end of the year, you donate twice this amount to charities, rounded down to the nearest whole dollar.

Those instructions can be used to solve the exercise.
