### ISSUE TITLE
In Connect exercise; wrong tests

### ISSUE THREAD

**Issue by henebb** [exercism/fsharp#984]
Hi! Either I'm not understanding the exercise, or there's an error in the tests :) 

- Check the "X wins crossing from left to right" test. The board is 4 columns but 5 rows. There shouldn't be a winner, but the test says Black should win.
- Same with the "O wins crossing from top to bottom" test. It should be None, but the test expects White to win.
- Also check the "Nobody wins crossing adjacent angles" test. It says None. Which is correct. But not because of the test description, but because the board is 4 columns and 5 rows :)

**Comment by ErikSchierboom** [comment]
@henebb The exercise is directly based on the data in https://github.com/exercism/problem-specifications/blob/main/exercises/connect/canonical-data.json. Could you create an issue there? Once the issue is fixed there, we can update the F# tests.

**Comment by henebb** [comment]
The description says "need _not_ to be fair". My bad 😆
