### ISSUE TITLE
Ability to run tests while offline

### ISSUE THREAD

**Issue by gilgamec** [exercism/fsharp#985]
(I'm not sure where this should go; this seems like the repo for the user-facing part of the F# track. Feel free to delete if there's a better home for it.)

I'd like to be able to work on exercism problems while I'm not connected to the internet; on a bus, on a plane, or just when my wifi isn't working. F# is the first track I've been in where it looks like you have to be connected to run tests; at least, the suggested test command,

    dotnet test

requires access to the internet the first time or it won't run.

I get that you have to be connected to download the problem in the first place, but in tracks I've used in the past, I just downloaded the available problems and worked on a few of them at a time; it's just something more to remember that I have to run the first test immediately after I download it.

In case this requirement is a bug: My wifi dropped while I tried to test `lucians-luscious-lasagna` and I got:
```
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/exercism.tests/index.json'.
  Name or service not known (api.nuget.org:443)
    Name or service not known
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/exercism.tests/index.json'.
  Name or service not known (api.nuget.org:443)
    Name or service not known
/usr/share/dotnet/sdk/5.0.205/NuGet.targets(131,5): error : Failed to retrieve information about 'Exercism.Tests' from remote source 'https://api.nuget.org/v3-flatcontainer/exercism.tests/index.json'. [/home/___/exercism/fsharp/lucians-luscious-lasagna/LuciansLusciousLasagna.fsproj]
/usr/share/dotnet/sdk/5.0.205/NuGet.targets(131,5): error :   Name or service not known (api.nuget.org:443) [/home/___/exercism/fsharp/lucians-luscious-lasagna/LuciansLusciousLasagna.fsproj]
/usr/share/dotnet/sdk/5.0.205/NuGet.targets(131,5): error :   Name or service not known [/home/___/exercism/fsharp/lucians-luscious-lasagna/LuciansLusciousLasagna.fsproj]
```

**Comment by ErikSchierboom** [comment]
We can't really support this, as it would involve us having to check-in all the dependencies which would make the initial exercise download huge (besides it being bad practice). The great thing is that all the F# exercises use just a couple of dependencies. Once you've downloaded them once, you don't need to download them another time. So this is really just a one-time downloaded, after which you can work offline as desired.

> but in tracks I've used in the past [...]

Some tracks indeed do not need internet, but many others do. There is not much the tracks themselves can do about this, as it is often the way their languages work.
