### ISSUE TITLE
lens-person: Dependency required and not part of test-runner env

### ISSUE THREAD

**Issue by SaschaMann** [exercism/fsharp#988]
From the bug reports:

---

I cannot submit fsharp/lens-person because it fails to build, both in the automatic validator, and the online editor.

This is the error:
```
We received the following error when we ran your code:

/usr/share/dotnet/sdk/5.0.100/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
/usr/share/dotnet/sdk/5.0.100/NuGet.targets(131,5): error :   Resource temporarily unavailable (api.nuget.org:443)
/usr/share/dotnet/sdk/5.0.100/NuGet.targets(131,5): error :   Resource temporarily unavailable
```

It does not appear to be "temporary" though.  I'm guessing it's because the exercise includes an additional dependency beyond the usual set, and perhaps outgoing connections are disallowed from the build container?

My tests pass locally, and I don't really need to use the online editor, but compared to the old exercism, I now also cannot do a basic submit.

**Comment by ErikSchierboom** [comment]
With https://github.com/exercism/fsharp-test-runner/pull/31 merged, this should now be working again.
